name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  docker-build:
    needs: [go-build, node-build]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Backend Docker image
      run: docker build ./backend --file Dockerfile --tag vb-events-backend:ci

    - name: Build the Frontend Docker image
      run: docker build ./frontend --file Dockerfile --tag vb-events-frontend:ci

    - name: Scan the Backend Docker image
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: vb-events-backend:ci
        format: table
        exit-code: '1'
        ignore-unfixed: true
        severity: CRITICAL,HIGH

    - name: Scan the Frontend Docker image
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: vb-events-frontend:ci
        format: table
        exit-code: '1'
        ignore-unfixed: true
        severity: CRITICAL,HIGH
